### ISSUE TITLE
Issue with get_images: RuntimeError: null pointer passed for argument "frame_ref"

### ISSUE THREAD

**Issue by AbdelRahmanNasser20** [vstadnytskyi/intel-realsense-devices#13]
def get_images(self):
        """
        Setting up a dict containing images that are recived from the pipline
        Parameters: Nothing
        Returns: Dict containing images  
        """

        f = self.pipeline.wait_for_frames()
        # accel = (f[3].as_motion_frame().get_motion_data())
        # gyro =  (f[4].as_motion_frame().get_motion_data())

        color = f.get_color_frame()
        infrared = f.get_infrared_frame(0)
        depth = f.get_depth_frame()

        color_img = np.asanyarray(color.get_data())
        ir_img = np.asanyarray(infrared.get_data())
        depth_img = np.asanyarray(depth.get_data())

        return {"color": color_img, "depth" : depth_img, "infared" : ir_img}

I get the following issue:
  File "c:/Users/Abdel Nasser/Desktop/L151 Camera/intel-realsense-devices/intel_realsense_devices/driver.py", line 183, in <module>
    plt.imshow(driver.get_images()['depth'])
  File "c:/Users/Abdel Nasser/Desktop/L151 Camera/intel-realsense-devices/intel_realsense_devices/driver.py", line 169, in get_images
    ir_img = np.asanyarray(infrared.get_data())
RuntimeError: null pointer passed for argument "frame_ref"

When I remove the infrared related lines it works. Is there a easier way to raise an issues without having to copy over the code.

**Comment by vstadnytskyi-FDA** [comment]
One of a very powerful tools in Python is PythonDeBugger (PDB)

add line

`from pdb import pm # pm stands for post mortem`

to you codes. and Now when you have an error, you can run `pm()` and get into debugging mode. In this more, you recover the state of the kernel at the point of crashing. You can access all the variable, etc.
 
Why do you need to pass '0' to function in this line `infrared = f.get_infrared_frame(0)`

**Comment by AbdelRahmanNasser20** [comment]
Solution: Stream was not configured. 
self.config.enable_stream(rs.stream.*) => where * == camera/image type attribute.

Below is the url for that attribute.
https://intelrealsense.github.io/librealsense/python_docs/_generated/pyrealsense2.stream.html
